<?php

namespace OmsBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use OmsBundle\Entity\Company;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Company::class) :
                $metaData
        );
    }

    /**
     * @param Company $company
     * @throws ORMException
     */
    public function insert(Company $company)
    {
        try {
            $this->_em->persist($company);
            $this->_em->flush();
        } catch (OptimisticLockException $e) {

        }
    }

    /**
     * @param Company $company
     * @throws ORMException
     */
    public function update(Company $company)
    {
        try {
            $this->_em->merge($company);
            $this->_em->flush();
        } catch (OptimisticLockException $e) {

        }
    }

    /**
     * @param Company $company
     * @throws ORMException
     */
    public function remove(Company $company)
    {
        try {
            $this->_em->remove($company);
            $this->_em->flush();
        } catch (OptimisticLockException $e) {

        }
    }

}
