<?php

namespace OmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CutOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CutOrderRepository extends EntityRepository
{
}
