<?php

namespace OmsBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use OmsBundle\Entity\Price;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Price::class) :
                $metaData
        );
    }

    /**
     * @param Price $price
     * @throws ORMException
     */
    public function insert(Price $price)
    {
        try {
            $this->_em->persist($price);
            $this->_em->flush();
        } catch (OptimisticLockException $e) {

        }
    }

    /**
     * @param Price $price
     * @throws ORMException
     */
    public function update(Price $price)
    {
        try {
            $this->_em->merge($price);
            $this->_em->flush();
        } catch (OptimisticLockException $e) {

        }
    }

    /**
     * @param Price $price
     * @throws ORMException
     */
    public function remove(Price $price)
    {
        try {
            $this->_em->remove($price);
            $this->_em->flush();
        } catch (OptimisticLockException $e) {

        }
    }
}
