<?php

namespace OmsBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use OmsBundle\Entity\Role;
use Doctrine\ORM\Mapping;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                Mapping\ClassMetadata $metaData = null)
    {
        parent::__construct($em,
            $metaData == null ?
                new Mapping\ClassMetadata(Role::class) :
                $metaData
        );
    }
    public function insert (Role $role){
        try {
            $this->_em->persist($role);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }


}
