# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        OmsBundle\Entity\User: bcrypt
    providers:

        database_users:
            entity: { class: OmsBundle:User, property: username }

    firewalls:
        secured_area:
            # this firewall applies to all URLs
            pattern: ^/

            # but the firewall does not require login on every page
            # denying access is done in access_control or in your controllers
            anonymous: true

            # This allows the user to login by submitting a username and password
            # Reference: http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                # The route name that the login form submits to
                check_path: security_login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                login_path: security_login
                # Secure the login form against CSRF
                # Reference: http://symfony.com/doc/current/cookbook/security/csrf_in_login_form.html
                default_target_path: cutorder_index
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: security_login
            logout_on_user_change: true


    access_control:
    # this is a catch-all for the admin area
    # additional security lives in the controllers
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/price', roles: [ROLE_ADMIN, ROLE_USER]}
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: [ROLE_ADMIN, ROLE_USER, ROLE_GUEST] }